name: Push to ECR

on:
  push:
    branches:
      - main

jobs:
  push-to-ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-2
          aws ecr get-login-password --region us-east-2| docker login --username AWS --password-stdin canavan-a.dkr.ecr.us-east-2.amazonaws.com

      - name: Build and tag Docker image
        run: |
          docker build -t test-image .
          docker tag test-image:latest canavan-a.dkr.ecr.us-east-2.amazonaws.com/my-containers:latest

      - name: Push Docker image to ECR
        run: |
          docker push canavan-a.dkr.ecr.us-east-2.amazonaws.com/my-containers:latest
