name: Push to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        working-directory: ./server
        run: docker build -t my-image .

      - name: Tag Docker image
        run: docker tag my-image canavan-a.dkr.ecr.us-east-2.amazonaws.com/my-containers:latest

      - name: Push Docker image to ECR
        run: >
          docker login -u AWS -p ${{ secrets.AWS_SECRET_ACCESS_KEY }} https://canavan-a.dkr.ecr.us-east-2.amazonaws.com
          docker push canavan-a.dkr.ecr.us-east-2.amazonaws.com/my-containers:latest

