name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_CLIENT_EMAIL }}
          export_default_credentials: true

      - name: Configure Docker
        uses: docker/setup-qemu-action@v1
      - name: Build and push Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/your-app:latest .

          gcloud auth configure-docker

          docker push us-central1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/your-app:latest
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCLOUD_CLIENT_EMAIL }}
      


