name: Deploy Container

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      
          
      - name: Deploy a new revision to Google Cloud Run
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          SERVICE_NAME: picstone-cd
          REGION: us-central1
        run: |
          gcloud run deploy picstone-cd --image=us-central1-docker.pkg.dev/$GOOGLE_PROJECT/my-containers/my-container:latest --platform=managed --region=us-central1 --quiet
